alces-software/metalware

deployment/epel/files/httpddeployment.kscomplete
deployment/epel/scripts/install/deploymentserver.sh
deployment/epel/scripts/install/httpserver.sh
etc/templates/kickstart/compute.erb
lib/ruby/lib/alces/stack/boot/run.rb
lib/ruby/lib/alces/stack/iterator.rb
lib/ruby/lib/alces/stack/kickstart.rb
lib/ruby/lib/alces/stack/kickstart/run.rb
scripts/install

Autodelete boot --kickstart

---

test/combiner-test.rb
test/hosts-test.rb
test/status/job-test.rb
test/status/monitor-test.rb
test/status/run-test.rb
test/testsuite.rb

Test suite for the new status tool.
Tests the code that will be included in additional PR to `feature/refactored-status`

Created tests suite for `status` tool

---

etc/profile.d/base.sh
scripts/os/el7.sh

Installing the missing dependencies that is preventing metalware
from installing nicely

Install missing dependencies

---

src/base_command.rb
src/bash.rb
src/cli.rb

Just some minor refactoring; based off https://github.com/alces-software/metalware/pull/68.

Refactor commands module

---

spec/commands/hosts_spec.rb
spec/integration/build_spec.rb
spec/templater_spec.rb
src/build_files_retriever.rb
src/commander_extensions.rb
src/commands/build.rb
src/constants.rb
src/deployment_server.rb
src/exceptions.rb
src/node.rb
src/nodeattr_interface.rb
src/nodes.rb
src/output.rb
src/templater.rb

This PR either addresses or removes various comments made about things to come back to in future, in order to try and tidy things up a bit before releasing Metalware 2.0.0. Everything left did not seem worth addressing currently as they would require too much work for the benefit to be gained by addressing them. See individual commits for full details.
Based on branch under review in https://github.com/alces-software/metalware/pull/93.

Address various TODO/XXXs

---

CHANGELOG.md

@WilliamMcCumstie can you have a quick look at this; if there's nothing I've missed I'll put out 2.0.0.

Update CHANGELOG for 2.0.0

---

Gemfile.lock
spec/fixtures/configs/integration-test.yaml
spec/fixtures/minimal-repo/config/domain.yaml
spec/fixtures/minimal-repo/pxelinux/default
spec/integration/build_spec.rb

@WilliamMcCumstie can you check that this fixes the issues for you on `master`?

Fix build integration test failures

---

src/cli_helper/config.yaml

Hopefully made include-groups description clearer

---

spec/dependency_specifications_spec.rb
src/commands/build.rb
src/dependency_specifications.rb

Fixes couple of issues as mentioned in https://trello.com/c/2tL6Q2CP/154-add-in-optional-dependency-for-nodes-on-node-answers.

Add some optional dependencies

---

spec/command_helpers/configure_command_spec.rb
src/command_helpers/base_command.rb
src/command_helpers/configure_command.rb
src/commands/configure/domain.rb
src/commands/configure/group.rb
src/commands/configure/node.rb
src/commands/configure/rerender.rb
src/commands/each.rb
src/commands/render.rb
src/commands/repo/use.rb
src/commands/status.rb
src/commands/view_answers/domain.rb
src/commands/view_answers/group.rb
src/commands/view_answers/node.rb
src/commands/view_config.rb

We only ever instantiate our command classes, and don't run any other methods from outside the classes, so we can just make everything in these private. Based on https://github.com/alces-software/metalware/pull/150.

Privatise all the things

---

spec/commands/build_spec.rb
spec/minimal_repo.rb
src/commands/build.rb

This PR contains various refactoring done prior to implementing the PR I'm about to base off this. There shouldn't be any new functionality here, just various tweaks and refactorings made prior to the next branch; see individual commits for details. This is based off https://github.com/alces-software/metalware/pull/153.

Various build command and tests refactoring

---

spec/commands/build_spec.rb
src/build_methods/basic.rb
src/build_methods/build_method.rb
src/build_methods/kickstart.rb

See https://github.com/alces-software/metalware/commit/23aea9900399f28b552af092f09f8f4ad4e43491 for details.

Fix basic build dependency error (fixes #167)

---

spec/configurator_spec.rb
src/configurator.rb

See https://github.com/alces-software/metalware/commit/5e06759becf234f87ad967c1b6c41880ed3d5eda for main details.

Fix inheriting of false boolean answers

---

src/templating/magic_namespace.rb
src/templating/repo_config_parser.rb

Fixes various small bugs. Review commit messages for further details

Fixes various small bugs

---

scripts/install
scripts/lib/install.functions.sh
scripts/os/el6.sh
scripts/os/el7.sh
src/command_helpers/orchestrate_command.rb
src/commands/console.rb
src/commands/ipmi.rb
src/commands/orchestrate/create.rb
src/commands/orchestrate/destroy.rb
src/vm.rb

This addresses the comments in #270 and includes the certificate generation at metalware install stage

KVM orchestration fixes/improvements

---

scripts/install
src/vm.rb

KVM orchestration fixes

---

spec/commands/plugin/disable_spec.rb
spec/commands/plugin/enable_spec.rb
src/commands/plugin/list.rb
src/plugins.rb

This PR contains some minor refactoring of some plugins-related stuff, will merge straight through in a minute.

Minor plugins refactoring

---

spec/answers_table_creator_spec.rb
spec/validation/answer_spec.rb
spec/validation/loader_spec.rb
src/answers_table_creator.rb
src/commands/view_answers/group.rb
src/configurator.rb
src/dependency.rb
src/gui/app/models/configure/questions.rb
src/plugins/configure_questions_builder.rb
src/validation/answer.rb
src/validation/loader.rb

Based on #319, please merge it first.
This PR contains various small fixes. Please see commits for details. Fixes the issues contained within #311

Various minor fixes

---

src/configurator.rb

Various refactoring in the `Configurator` class for some things I noticed while I was there, see commits for details. Based on #331.

Configurator refactoring

---

spec/commands/power_spec.rb
src/commands/ipmi.rb

Fixes https://github.com/alces-software/metalware/issues/337.

Make `power` (and `ipmi`) fault tolerant

---

spec/alces_utils.rb
spec/hash_mergers/hash_merger_spec.rb
src/configurator.rb
src/configurator/question.rb
src/hash_mergers/answer.rb
src/hash_mergers/hash_merger.rb
src/question_tree.rb
src/validation/answer.rb
src/validation/loader.rb

Based on #342, please merge it first.
This PR contains various tweaks suggested during the `Configurator` refactor. Please see commits for details.

Final tweaks for Configurator refactor

---

spec/alces_utils.rb

See commit for full details. The race condition occur due to the threading of the build process interacting with how `AlcesUtils` mocked `nodeattr`.
The mocking of `nodeattr` required the `FakeFS` to be turned off briefly. This was causing an error because it essentially makes the faked files disappear. However it can only cause an issue due to threading.
The fix is to use `bash` commands instead of turning off `FakeFS`. The bash commands always act on the real filesystem so they provide a convenient way to mock `nodeattr` without having to turn off `FakeFS`.
Please note, there is still another race condition as part of the `Status::Monitor` tests. Partially fixes the bug in #293.

Fix race condition during the build specs

---

docs/design/04-asset-records.md

Create planning document for asset records

---

spec/utils/editor_spec.rb
src/utils/editor.rb

This PR adds the tests and functionality for the `open_copy` method with the purpose of copying and/or editing files

Edit/Copy Utility

---

spec/namespaces/asset_array_spec.rb
src/commands/view.rb
src/namespaces/asset_array.rb

This makes a bunch of small changes concerning `AssetArray`. See commit messages for details.
Fixes cards:
https://trello.com/c/W7DWnGdo/258-make-alcesassetsfindbyname-more-robust
https://trello.com/c/q2GRTmqb/253-make-alcesassets-display-all-the-assets-when-called-in-the-view-command

Various small tweaks to improve AssetArray

---

docs/design/05-asset-layout.md

Initial plan for creating asset layouts.

Create scoping document for asset layouts

---

spec/alces_utils.rb
spec/commands/asset/edit_spec.rb
spec/commands/layout/edit_spec.rb
spec/shared_examples/record_edit_command.rb
src/cli_helper/config.yaml
src/commands/layout/edit.rb

Using `metal layout edit` it is possible to now edit any existing layouts, this functions much like `asset edit`.

Implement the layout edit command

---

spec/shared_examples/record_add_command.rb
src/asset_builder.rb
src/cli_helper/config.yaml
src/command_helpers/layout_editor.rb
src/commands/layout/add.rb
src/records/layout.rb

With this PR it is now possible to add a `layout` from either a `type` or another `layout`

Add a layout from a type or a layout

---

src/build_event.rb
src/build_methods/kickstarts/kickstart.rb
src/commands/build.rb
src/templater.rb
src/templating/renderer.rb

Based off #418, please merge it first.
See commit for details: https://github.com/alces-software/metalware/commit/827b1441f12f801c80f8655b49f88b3ba54706b6
Fixes #271 
This PR also contains various small other changes. See commits for details.

Fix messages during the `local` build

---

src/namespaces/node.rb

Address #437 with chomp

---

CHANGELOG.md
docs/release-process.md

Plus minor related changes; see commits.

Update changelog for 2018.2.0-rc3

---

CHANGELOG.md
docs/release-process.md

Update CHANGELOG for 2018.3.0-rc3, and correct entries for recent releases.

Update changelog for 2018.3.0-rc3

---

src/cli_helper/config.yaml

Allow --answers for local
