alces-software/metalware

etc/templates/dhcp, lib/actions/each, lib/ruby/lib/alces/stack/hunter/cli.rb, lib/ruby/lib/alces/stack/hunter/listener.rb
Fix includes the each tool specified in #1 
It also includes the updates to hunter that log the output to /var/log/metalware/hunter.log. Hunter now has the option to update the dhcpd.hosts as mentioned in #3
=> Hunter each and update dhcp

lib/ruby/lib/alces/stack/hosts/cli.rb, lib/ruby/lib/alces/stack/hosts/run.rb, lib/ruby/lib/alces/stack/hunter/cli.rb, lib/ruby/lib/alces/stack/templater.rb
Fixed some bugs in metal hosts if no inputs where given and fixed the default template in hunter.
Updated the templater so it recursively replaces the parameters. It is now possible to reference a parameter tag within another parameter. The recursion limit is 100.
=> Recursive templater

lib/ruby/lib/alces/stack/kickstart/cli.rb, lib/ruby/lib/alces/stack/status/cli.rb
Required changes the CLI to match the new `status` tool. Also removes references to some logs that no longer exist in both `kickstart` and `status`
=> Changes to CLI

lib/ruby/lib/alces/stack/options.rb
Created the `Options` parser which converts the hash input from the `cli` to a object that can be queried  form the `action`.
I believe is will be removed in the updated version of metalware but is required for `status1.2` to work
=> Added options parser class

metalware-new/spec/commands/build_spec.rb, metalware-new/spec/commands/hosts_spec.rb, metalware-new/spec/integration/build_spec.rb, metalware-new/spec/spec_utils.rb, metalware-new/spec/templater_spec.rb, metalware-new/src/commands/build.rb, metalware-new/src/commands/dhcp.rb, metalware-new/src/commands/hosts.rb, metalware-new/src/commands/render.rb, metalware-new/src/nodes.rb, metalware-new/src/templater.rb
This PR contains a few changes to how the `Templater` interface works to support what I'm working on and to try and make the templating simpler/clearer/easier to test. See commit messages for the details of the changes.
There's quite a lot of additions/deletions here but it's mostly just churn in the tests and other files due to the interface when using the `Templater` changing; the important changes are in `metalware-new/src/templater.rb`. @WilliamMcCumstie: No need to look at this in great detail but if you want to take a quick look to see if you have any thoughts then that would be useful :slightly_smiling_face:.
=> Refactoring templater

metalware-new/spec/fixtures/configs/integration-test.yaml, metalware-new/spec/fixtures/configs/unit-test.yaml, metalware-new/src/config.rb, metalware-new/src/metal_log.rb, metalware-new/src/templater.rb
Carry on from the work on the logger. Please merge #55 before this one.
Modified `MetalLog` to override the base `warn` method. Now `MetalLog.warn` will take a message and log it to both `stderr` and the log file. 
`Templater` uses the `warn` when it tries to use a parameter in the `erb` template that is not defined. This is done by creating a wrapper around both `RecursiveOpenStruct` and `MagicNamespace`. 
ERB now receives a `binding` from `TemplaterRecursiveOpenStruct` which is a wrapper around `RecursiveOpenStruct`. If `RecursiveOpenStruct` return a nil value to the templater, the wrapper log it as a `warning`.
However ERB first quires `TemplaterRecursiveOpenStruct` for the `MagicNamespace` object. Then it quires `MagicNamespace` separately for the exact value (e.g. index). Therefore …
=> Templater logs warnings when it tries to use missing parameters

metalware-new/spec/commands/render_spec.rb, metalware-new/spec/fixtures/configs/integration-test.yaml, metalware-new/spec/fixtures/configs/unit-test.yaml, metalware-new/src/cli.rb, metalware-new/src/commands/base_command.rb, metalware-new/src/config.rb, metalware-new/src/exceptions.rb, metalware-new/src/metal_log.rb
Continuation of work with the logger. Please merge #57 first.
Added an error class `StrictWarningError` and the `--strict` option to the `cli`. When in `--strict` mode, the logger will convert all `warnings` to `StrictWarningError` which is then `raised`. Note, the error does not get logged when it is raised but alternatively when it causes a `fatal` error in the `BaseCommand`. This means that it can be caught.
The `--strict` option is stored in the `@config` object. However as it comes from the `cli` I have added an `OpenStruct` as more `cli` options are expected.  Therefore you access it by: `config.cli.strict`.
Also added a test of `--strict` using `render`. I had to add a few config parameters and reset the log to prevent issues during testing. This is because `config` and `MetalLog` …
=> --strict converts warnings to errors

metalware-old/lib/ruby/lib/alces/stack/boot/run.rb, metalware-old/lib/ruby/lib/alces/stack/hosts/cli.rb, metalware-old/lib/ruby/lib/alces/stack/hunter/cli.rb, metalware-old/lib/ruby/lib/alces/stack/hunter/listener.rb, src/cli.rb, src/commands/base_command.rb, src/metal_log.rb, src/output.rb
The CLI now has a global option, `--quiet` which causes standard error to  be redirected to /dev/null. This does not affect standard error and thus we will still get the warnings. 
Also I have included it as part of the `CLI` itself. This means it will not be available if we want to run the ruby tools directly in the future. 
However this looks to meet the requirements at this point in time.
=> Suppress output with `--quiet`

src/cli.rb
Simple fix to display help when you run `metal`. 
Was looking to do the same for `repo` but that's much harder as `repo use` and `repo update` are defined separately
=> Display the usage if not command input

scripts/install
Link certain files in to Metalware dir; these can then be retrieved by a request to a `/metalware/system/$file` route on the Metalware deployment server.
Trello: https://trello.com/c/oFRKSD7A/29-have-required-urls-work-on-metalware-deployment-server.
=> Make system files available on Metalware server

scripts/install, spec/defaults_spec.rb, src/cli.rb, src/commands/base_command.rb, src/commands/build.rb, src/commands/dhcp.rb, src/commands/hosts.rb, src/commands/hunter.rb, src/defaults.rb
Based on branch under review in https://github.com/alces-software/metalware/pull/63.
Trello: https://trello.com/c/M7EY4cUF/35-show-default-values-for-options-in-command-help.
=> Show defaults in help

spec/commands/build_spec.rb, spec/commands/hosts_spec.rb, spec/fixtures/configs/repo-unit-test.yaml, spec/integration/build_spec.rb, spec/templater_spec.rb, src/commands/build.rb, src/commands/dhcp.rb, src/commands/hosts.rb, src/commands/render.rb, src/commands/repo/update.rb, src/commands/repo/use.rb, src/constants.rb, src/templater.rb
This PR fixes an issue where we would sometimes read the path to the repo from the config and sometimes from a hard-coded constant. The key commit with details is in https://github.com/alces-software/metalware/commit/e35bb3cb7535d9c329f0df332a282f281753026b.
This seems a good idea generally, but was particularly important for another feature I've added, the PR for which I'll base off of this.
=> Get repo from config always

spec/commands/build_spec.rb, spec/commands/hosts_spec.rb, spec/fixtures/configs/repo-unit-test.yaml, spec/integration/build_spec.rb, spec/spec_utils.rb, spec/templater_spec.rb, src/base_command.rb, src/commands/build.rb, src/commands/dhcp.rb, src/commands/hosts.rb, src/commands/render.rb, src/commands/repo/update.rb, src/commands/repo/use.rb, src/constants.rb, src/exceptions.rb, src/repo.rb, src/templater.rb
This PR makes commands which require a repo not run before a repo has been set up, and instead fail fast and descriptively.
Based off https://github.com/alces-software/metalware/pull/67; Trello: https://trello.com/c/TnJw3paI/38-commands-which-require-a-repo-to-work-should-gracefully-fail-before-a-repo-has-been-cloned.
=> Require repo before running repo commands

spec/fixtures/unset_parameter_template.erb, spec/templater_spec.rb, src/exceptions.rb, src/templater.rb
This PR improves the error shown when an attempt is made to access a property on an unset template parameter; see https://github.com/alces-software/metalware/commit/17fade5c2b2090b657c618589e0283ef2e15ff29 for details.
This PR is a fix for https://trello.com/c/lJuWATLd/51-error-when-running-bin-metal-render-var-lib-metalware-repo-kickstart-default-testnode01---trace; it also addresses https://trello.com/c/5DrQ5WUr/52-make-clear-when-errors-are-template-errors-rather-than-metalware and should resolve that unless we can think of other ways we should make this clear to users.
This PR is based on https://github.com/alces-software/metalware/pull/69.
=> Better handle accessing unset parameters

libexec/ipmi, src/cli.rb
Based on #72 as I needed the new name of BashCommand
The ipmi script has been moved into libexec is being called through the
BashCommand. However there is a clash between Metalware CLI and ipmi's.
It might be worth while rewriting ipmi so that it is ran through ruby
instead of exec.
Also we should consider only using long option tag (e.g. `--opt-tag`)
and removing `-c <config>` tag. This is to prevent conflicts as ruby
will assume you are referring to both simultaneously with a undefined
result. In the meantime, I have resolved a conflict by changing the
ipmi command tag from `-c` to `-k`.
Also commented out the dummy examples in the CLI so they don't get
rendered.
=> Migrated ipmi to metalware version 2

spec/iterable_recursive_open_struct_spec.rb, src/exceptions.rb, src/iterable_recursive_open_struct.rb, src/templater.rb
When writing Metalware templates it is sometimes desirable to be able to iterate through a set of key-value pairs, rather than needing to access parameters individually; previously this was not possible (without
writing a convoluted template).
This commit allows this by adding a new class to be used for the template parameters loaded from the repo config, which functions the same as `RecursiveOpenStruct` but with an additional `each` method.
This seemed the simplest way to add this functionality without making future issues and confusion likely; we do not want to make this class have all `Enumerable` methods otherwise issues would occur when setting any properties with the same names in the config.
=> Allow iterating through template parameters

src/cli.rb
This PR is dependant on the new version of Commander. Please merge the following PR first:
https://github.com/alces-software/commander/pull/1
Created a `repo` command that appears in the main help. It is responsible for display the help for it's subcommands. The sub commands (`update` and `use`) have been removed from the main help as they now appear in the sub help.
=> Update Metalware to use Commanders new subcommands

docs/design/01-metalware-improvements.md, docs/design/02-topologies.md, docs/design/README.md
The important doc related to topologies is https://github.com/alces-software/metalware/compare/dev/docs?expand=1#diff-7633f31d52d6afaac7f6adf486a7e485.
=> Add Metalware design docs, in particular for topologies

spec/configurator_spec.rb, src/configurator.rb, src/exceptions.rb
This PR adds a `Configurator` class, which is an easily testable class to be used in our `configure` commands to perform the configuration process.
This works by loading a given `configure.yaml` file, asking the specified group of questions using appropriate `HighLine` methods based on their `type`, and then saving the answers to the specified `answers` file.
There is not a specific Trello card for this, but it will support a future PR adding the basic `configure` commands.
=> Add Configurator class

README.md, docs/templating-system.md
Some documentation on the Metalware templating system, which is one of the more complicated parts of Metalware and is also not suitably covered by the existing README or design docs.
Happy to receive any comments, or just add commits to the branch if that's simpler.
Trello: https://trello.com/c/tLNKYa1f/50-document-new-metalware-including-magic-namespace.
=> Document Metalware templating system

src/commands/configure/group.rb, src/commands/configure/node.rb
`metal configure group` and `metal configure node` were not including the correct file extension when saving their answers; this corrects that.
=> Correct `configure` commands to use correct files

docs/templating-system.md, spec/commands/build_spec.rb, spec/commands/hosts_spec.rb, spec/integration/build_spec.rb, spec/node_spec.rb, spec/templater_spec.rb, src/node.rb, src/nodes.rb, src/templater.rb
This PR makes the node `index` used when templating be consistent across invocations of different commands which template for the same node. For example, given:
```
node[01-05] nodes,domain
```
then `metal build -g nodes` and `metal build node05` will both use an `index` of `4` for `node05`, whereas previously they would use `4` and `0` respectively.
This does have the limitation described [here](https://github.com/alces-software/metalware/blob/bd781fd6630350344e61c6afa332be2e6e5a95fe/spec/node_spec.rb#L168,L177); however this situation should be improved with future changes, as described in https://trello.com/c/XjtdbEHm/80-improve-how-indexes-work, which this PR is an initial step towards resolving.
=> Make node indexes consistent across different commands

Gemfile, spec/commands/configure/group_spec.rb, src/commands/configure/group.rb, src/constants.rb, src/node.rb, src/utils.rb
Based on branch under review in https://github.com/alces-software/metalware/pull/97, and working towards resolving the same card.
This PR adds caching of primary groups as each new `metal configure group` command is run, which is a step towards adding a `group_index` for each primary group. The key commit here is https://github.com/alces-software/metalware/commit/231397059879c1e601fdd06ffe521a3d4f6523d2, so see that for more details.
=> Cache primary groups as new groups configured

CHANGELOG.md, spec/configurator_spec.rb, src/configurator.rb, src/utils.rb
Continuation of Typology questions. Please merge #91 first
When loading the default answer, the answer file is checked first. If an old answer is found, then that is used as the default. Otherwise the default in `configure.yaml` is used.
=> Define configure default answers as the previously recorded answer

Gemfile.lock, src/cli_helper/parser.rb
This PR fixes two bugs that where identified in hunter:
The first bug is when `-s` is used with `hunter`, it truncates the `UDP` packets. This is because `Pcap` always passed the `ARGV` array into `OptionParser`. This has been fixed in Pcap (link below). In short, `Pcap` no longer parses the `ARGV` array unless it isn't initialised with any inputs.
https://github.com/alces-software/ruby-pcap/commit/966ce3739d7c91c15032b3a85095c7400565841f
The second bug is when an integer value is entered into the cli with a leading zero (e.g. `-s 035`). As `Integers` are converted according to their prefixed value, '035' is converted as an octal to 29. Now the `cli_helper` will automatically set all `Integers` as `DecimalIntegers`. A bug patch also needed to be included in `Commander` (link below). This …
=> Fix hunter bugs

spec/build_files_retriever_spec.rb, spec/commands/build_spec.rb, spec/commands/hosts_spec.rb, spec/fixtures/configs/empty-repo.yaml, spec/fixtures/configs/repo-unit-test.yaml, spec/fixtures/configs/unit-test.yaml, spec/templater_spec.rb, src/bash_command.rb, src/config.rb
The `repo_configs_path` config parameter has still be contributing to bugs in the tests despite being deprecated. This PR removes it completely from the code base.
Also the bug in `ipmi` was due to ruby stripping the quotes off the cli causing the command to be parsed as separate arguments in bash. This has now been fixed by directly passing the input array into `exec`.
Fixes: #102
=> Fixes ipmi and a range of other bugs

docs/design/02-topologies.md, spec/configurator_spec.rb, src/configurator.rb
Configure questions are now required by default. This means that the
user will be prompted to renter an answer if they do not give one and
it does not have a default.
A new optional tag can be included with the questions, which means
an empty input is a valid response. The optional tag must evaluated
to a truthy value.
Note that when HighLine re-prompts for an input, it uses inspect to
generate the message. This gives crazy responses such as:
`must match <proc:/some/file/path-352random-other-stuff>`
As this isn't very useful to the user, a HighLinePrettyValidateProc
class is used. This class overrides the inspect method so that it
gives nicer prompts to the user.
=> Enforce required and allow optional questions

spec/templater_spec.rb
Based on https://github.com/alces-software/metalware/pull/106. This is just some refactoring of the Templater's magic namespace tests, to in particular use `FakeFS` and `FileSystem`. Submitting this now to keep it separate from my next PR which will also touch the `MagicNamespace`.
=> Improve magic namespace tests

docs/templating-system.md, spec/filesystem.rb, spec/fixtures/cache/groups.yaml, spec/node_spec.rb, spec/templater_spec.rb, src/commands/configure/group.rb, src/constants.rb, src/exceptions.rb, src/node.rb, src/templater.rb
Based on https://github.com/alces-software/metalware/pull/107.
This PR adds a `group_index` parameter to the `alces` templater namespace, which returns a unique, consistent, index for the current node's primary group. This forms another part of the work towards https://trello.com/c/XjtdbEHm.
=> Add `group_index`

spec/fixtures/answers/group_namespace_tests/domain.yaml, spec/fixtures/answers/group_namespace_tests/groups/testgroup.yaml, spec/templating/group_namespace_spec.rb, spec/templating/magic_namespace_spec.rb, src/node.rb, src/primary_group.rb, src/templater.rb, src/templating/configuration.rb, src/templating/group_namespace.rb, src/templating/magic_namespace.rb
Based on https://github.com/alces-software/metalware/pull/113.
This PR adds a `groups` function to the `alces` namespace, as discussed on Slack at https://alces.slack.com/archives/C5FL99R89/p1499856806970388. Currently `groups` will call the passed block once for each primary group (each group already configured with `metal group configure`), with each call passed a `GroupNamespace` for the current group. The `GroupNamespace` currently provides two properties: `name`, the group name, and `answers`, the `configure` answers for that group; this is the domain answers with the group answers merged in, as these are the only answers which are applicable to a particular primary group.
Access to the `nodes` will also be needed from a `GroupNamespace`, but this will follow in a future PR as this …
=> Add `groups` to `alces` namespace

src/templater.rb, src/templating/missing_parameter_wrapper.rb, src/templating/renderer.rb, src/templating/repo_config_parser.rb
Based on https://github.com/alces-software/metalware/pull/115.
This PR extracts some more parts of the `Templater` to two new classes, `RepoConfigParser` and `Renderer`, along with some other small refactoring. This is done as we need to use this functionality in other places now, and it makes sense to split this up a bit more in any case.
=> Extract more templater parts

spec/command_helpers/configure_command_spec.rb, spec/commands/configure/group_spec.rb, spec/filesystem.rb, spec/fixtures/repo/config/domain.yaml, spec/fixtures/template.erb, spec/fixtures/unset_parameter_template.erb, spec/minimal_repo.rb, spec/templater_spec.rb, src/command_helpers/base_command.rb, src/command_helpers/bash_command.rb, src/command_helpers/configure_command.rb, src/commands/configure/group.rb, src/commands/hosts.rb, src/constants.rb, src/templating/magic_namespace.rb, src/templating/repo_config_parser.rb
This PR makes the hosts and genders files be re-rendered after each `configure` command, as the information used to generate these can change with any `configure` command. Some related changes are also included such as some testing improvements and conversion of boolean values when templating.
Trello: https://trello.com/c/HE3R0A3a/19-have-hosts-fully-render-the-hosts-file-in-a-single-pass and https://trello.com/c/KHcNThRO/115-have-genders-be-generated-based-on-configured-groups.
=> Render hosts and genders after each configure process

spec/configurator_spec.rb, src/configurator.rb
This PR makes some improvements to the `metal configure` commands. In particular, in addition to some test improvements, readline bindings are now available when entering input for questions, and defaults and the loading of old answers now work for questions of type `boolean`.
=> Configure command improvements

spec/command_helpers/configure_command_spec.rb, spec/commands/configure/group_spec.rb, spec/filesystem.rb, spec/nodeattr_interface_spec.rb, spec/spec_helper.rb, spec/spec_utils.rb, spec/system_command_spec.rb, spec/templater_spec.rb, src/command_helpers/configure_command.rb, src/constants.rb, src/exceptions.rb, src/io.rb, src/nodeattr_interface.rb, src/system_command.rb, src/templater.rb
If after a `configure` process an invalid `genders` file is rendered, then we now handle this by:
- reporting the error;
- not replacing the existing `genders` file;
- not rendering the `hosts` file, as this normally uses information obtained from the `genders` file using `nodeattr`;
- making the invalid rendered `genders` file available for inspection, at a location reported to the user.
=> Handle generating bad `genders` file

.gitignore, Makefile, spec/dependency_spec.rb, spec/integration/build_spec.rb, src/dependency.rb
A new optional hash can be included in the dependency_hash which indicates files that should be validated but does not throw an error if they do not exist.
The optional hash has the same syntax as a regular dependency_hash. At this point in time, the superfluous, however it will be needed once Answer Validation is included.
=> Allow optional files in Dependency

src/commands/view_config.rb
This PR is based on https://github.com/alces-software/metalware/pull/130 as it depends on a function added in that PR.
This fixes the issue raised in #136 by giving an informative error message when an attempt is made to `view-config` for a node which doesn't exist; I'll address the other aspect of that issue there.
=> Fix `view-config` error for unconfigured node (fixes #136)

spec/object_fields_hasher_spec.rb, src/object_fields_hasher.rb, src/templating/group_namespace.rb, src/templating/magic_namespace.rb
This commit introduces a module with a single function which will take an object and convert its methods and their values to the keys and values of a hash, with the optional ability to override what method is
used to get certain fields. This function is then used in the `MagicNamespace` and `GroupNamespace` when we convert them to hashes, so we don't need to manually specify the fields to include.
This function will of course only work for objects where all methods to be included can take no arguments, otherwise it will blow up as the methods won't be sent enough arguments.
As suggested in https://github.com/alces-software/metalware/pull/129#discussion_r129885647.
=> Dynamically decide namespace fields to hash

spec/build_files_retriever_spec.rb, spec/commands/each_spec.rb, spec/commands/status_spec.rb, spec/config_spec.rb, spec/dependency_specifications_spec.rb, spec/integration/build_spec.rb, spec/node_spec.rb, spec/nodeattr_interface_spec.rb, spec/slow/status/job_spec.rb, spec/slow/status/monitor_spec.rb, spec/spec_helper.rb, spec/templater_spec.rb
Run every test using `FakeFS` unless a truthy `real_fs` metadata value is passed; this prevents us polluting the real file system unless explicitly requested.
With this change it may be possible to simplify our use of `FileSystem` to not need to re-specify running in a `FakeFS` block around every test. However this would be quite a large refactoring and I'm not sure exactly how we'd want to do this at the moment, so I'm holding off on this until we've used this change for a bit.
=> Run every test using FakeFS unless specify not to

spec/cli_helper/parser_spec.rb, src/cli_helper/config.yaml, src/cli_helper/dynamic_defaults.rb, src/cli_helper/parser.rb, src/deployment_server.rb
This PR is a small addition, based on https://github.com/alces-software/metalware/pull/148. Now that we define the Metalware build interface in a consistent location, the rendered `server.yaml` file, this PR makes this build interface be the default interface used when `metal hunter` is run, rather than defaulting to `eth0` as we did previously. This is useful as this is almost always (or possibly just always) the interface we want to hunt on, so specifying this as the default means we should normally not need to pass this option.
=> Default hunter interface to build interface

scripts/os/el7.sh
This is needed by Metalware but was not being installed when installing Metalware on a machine running a minimal Centos install. Based on https://github.com/alces-software/metalware/pull/149; fixes https://trello.com/c/wga3bOlt.
=> Install gethostip in installer

src/commands/repo/update.rb, src/commands/repo/use.rb, src/exceptions.rb
Moves the last remaining errors into the unified `Exceptions` module. Also updated some of the error messages to be more descriptive. 
Card: https://trello.com/c/HLPwJePq/88-change-rugged-errors-to-metalware-errors-in-repo-use
=> Improve rugged errors

src/templating/group_namespace.rb
This PR is based off #147. Please merge it first.
Fixes #127 in which nodes would be duplicated in `/etc/hosts` if they are in a secondary group that is also a primary group. This is because, when we the hosts template is rendered, it loops through all the primary groups and all nodes belong to the group. This includes nodes that are in a different primary group and thus leads to duplicates.
This commit changes the behaviour to only loop through nodes that are part of the primary group and thus prevents duplicates.
=> Prevent duplicated nodes being listed in `/etc/hosts`

spec/commands/build_spec.rb, spec/fixtures/genders/simple_cluster, src/cli_helper/config.yaml, src/cli_helper/dynamic_defaults.rb, src/commands/build.rb, src/file_path.rb
This PR allows the PXELINUX and Kickstart templates used when building each node to be specified in the repo config for that node; following the meeting earlier the `--kickstart` and `--pxelinux` options have also been removed as they are now superfluous.
Trello: https://trello.com/c/ySxv4Z1s/155-pxe-and-kickstart-file-selection-in-configs. Corresponding repo change demonstrating use of this feature: https://github.com/alces-software/metalware-default/commit/00c0bf0f47cd47a6d42fbb46a91ccb410fbbc976.
=> Allow build template selection in configs (closes #143)

scripts/install, spec/commands/build_spec.rb, spec/minimal_repo.rb, src/build_methods.rb, src/build_methods/basic.rb, src/build_methods/build_method.rb, src/build_methods/kickstart.rb, src/commands/build.rb, src/file_path.rb, src/node.rb
This PR adds a `basic` `metal build` method for nodes, specified by the `build_method key in the repo config for a node, which is an alternative to the existing default Kickstart build method. See https://github.com/alces-software/metalware/commit/3fb444b94ca656e3216847fdb472cf15c7fa02c7 for the main details of what is involved in this method.
This resolves https://github.com/alces-software/metalware/issues/145 / https://trello.com/c/0wZYT7o9/164-add-basic-metal-build-method. It is based on https://github.com/alces-software/metalware/pull/155.
=> Add basic metal build method (closes #145)

spec/shared_examples/render_domain_templates.rb, spec/templater_spec.rb, spec/utils_spec.rb, src/domain_templates_renderer.rb, src/templater.rb, src/utils.rb
This PR changes how we handle rendering the `hosts` and `genders` files, to only render part of each file (which I call the 'managed section') and keep the rest of the file outside this section the same. This change will allow cluster admins to edit these files manually outside of this section, without needing to know or care about Metalware or how it changes these files.
An exact description of how this new rendering method functions depending on the existing file contents is in 3887a39d93ce2359b23dcc569aeffbe6e31f1ce0.
Based on #156; Trello: https://trello.com/c/pb8yT6qP.
=> Only rerender parts of hosts and genders

spec/fixtures/cache/groups.yaml, spec/fixtures/setup1/cache/groups.yaml, spec/group_cache_spec.rb, spec/node_spec.rb, spec/templater_spec.rb, src/exceptions.rb, src/group_cache.rb, src/node.rb, src/templating/magic_namespace.rb
Rather than having situations where this can be nil, which appears to just make templating more difficult without providing any benefit. Fixes issue discussed in https://github.com/alces-software/metalware/issues/161.
=> Make group_index always default to 0 (fixes #161)

spec/command_helpers/configure_command_spec.rb, src/command_helpers/base_command.rb, src/command_helpers/bash_command.rb, src/commands/build.rb, src/commands/configure/domain.rb, src/commands/configure/group.rb, src/commands/configure/node.rb, src/commands/configure/rerender.rb, src/commands/dhcp.rb, src/commands/each.rb, src/commands/hunter.rb, src/commands/remove/group.rb, src/commands/render.rb, src/commands/repo/update.rb, src/commands/repo/use.rb, src/commands/status.rb, src/commands/view_answers/domain.rb, src/commands/view_answers/group.rb, src/commands/view_answers/node.rb, src/commands/view_config.rb
This PR contains some tidying up of how we handle `args` and `options `in Metalware in some places. The important change here is https://github.com/alces-software/metalware/commit/9b4eb1ca1b82a993b29fbd297fb11450907acda9, which I made so I could access the `options` in multiple `configure` commands without needing to independently set these in their different `setup` methods (the details of this are unimportant; it will be in a future PR). The other changes came out of this, when I spotted a few places we could improve things; see commits for details.
=> Tidy up command args and options handling

src/cli_helper/config.yaml, src/commands/build.rb, src/exceptions.rb
First commit to implement the `edit` command. This commit concerns itself with how the `edit` command is used with `build`. At this point in time, the easiest way to implement it, is to split the build command into a render then build stages. This can be done with the use of flags on command line. At a latter date we can implement a more durable way to render the templates.
=> Split build command with edit flags

spec/dns/named_spec.rb, src/dns/named.rb
Fixes the issue logged in #108 
Named needs to be restarted when ever an update command is ran, not
only when it is started.
The methods have been slightly renamed. During setup, start_named is
called to run the bash commands which end with restart_named. But if
named, has already been setup, then restart_named is called only.
The test have been updated to reflect this
=> Restart named after each update

bin/autocomplete, etc/profile.d/base.sh, spec/shared_examples/render_domain_templates.rb, spec/templater_spec.rb, src/cli_helper/config.yaml, src/cli_helper/parser.rb, src/commands/edit.rb
Fairly small PR that implements the edit command. When I was linking in the autocomplete, I couldn't get it working well with relative paths, but I could use absolute. So instead of taking a relative path within the `rendered` directory, the user can tab complete `/var/lib/metalware/rendered` and then select the file from there.
It does mean the edit command can open any file in the filesystem, however this shouldn't be a big deal. Currently it uses the editor defined by VISUAL first or EDITOR as a fallback. If both haven't been set, then `vi` is used. Possible add a message about using `vi`?
=> Implement the edit command

docs/design/03-api-namespace.md, spec/templater_spec.rb, src/templating/magic_namespace.rb
This commit includes a fix to suppress the `alces.nodename` warning. Refer to 9caf103 for details.
Also contains the new spec document for a API to sit within the Templater ERB binding. Read doc for full details.
=> Suppress nodename warning and API spec

spec/command_helpers/configure_command_spec.rb, spec/configurator_spec.rb, src/cli_helper/config.yaml, src/command_helpers/configure_command.rb, src/configurator.rb
This PR adds a `--answers` option to the `configure` commands. Given a JSON mapping of question identifiers to answer values, the given answers will be saved instead of asking the configure questions and saving user input.
This was added to be used by the GUI, but this feature is exposed on the command line firstly because it may be useful, and secondly because we want the GUI features to match those available in the CLI as closely as possible.
Based on https://github.com/alces-software/metalware/pull/188.
=> Add `configure` `--answers` option

spec/command_helpers/configure_command_spec.rb, spec/commands/build_spec.rb, spec/commands/configure/domain_spec.rb, spec/commands/configure/group_spec.rb, spec/commands/configure/node_spec.rb, spec/commands/render_spec.rb, spec/shared_examples/render_domain_templates.rb, spec/spec_utils.rb, src/command_helpers/configure_command.rb, src/commands/configure/domain.rb, src/commands/configure/group.rb, src/commands/configure/node.rb, src/configurator.rb, src/utils.rb
This PR contains some refactoring to restructure some parts of the CLI to be more usable from the Metalware GUI. From the CLI perspective this should not contain any behaviour changes, but this makes several functions available in a few places which are needed by the GUI.
Based on https://github.com/alces-software/metalware/pull/189.
=> GUI supporting refactoring

spec/shared_examples/render_domain_templates.rb, spec/templater_spec.rb, spec/validation/configure_spec.rb, src/validation/configure.rb, src/validation/errors.yaml
Previously the `validate` method on `Validation::Configure` would return an object which contains if the validation succeeded or not. However this was not the object that `success?` used. Instead a stale instance variable was used and thus the validation could fail but still return true. This PR fixes the bug by saving the return object of `validate` as the instance variable.
Also added additional validation checks to allow empty strings as a valid default and to allow `Boolean` default values. Previously these caused the validation to fail but it wasn't being detected due to the previously mentioned bug.
=> Fixes Validation::Configure ignore failures bug

spec/minimal_repo.rb, spec/validation/answer_spec.rb, spec/validation/configure_spec.rb, src/cli_helper/config.yaml, src/commands/configure/self.rb, src/dependency.rb, src/file_path.rb, src/validation/configure.rb, src/validation/loader.rb
Based on the updated Validation. Please merge #178 first.
This is the first step for configuring the node metalware runs on. This will be defined as the `self` node. Currently the command runs the standard domain level template rerender.
However it does not add the `self` node to `/etc/hosts` or the genders file. I am not sure if this will be required so it has not been included in this PR. Future PR's will allow the building of the `self` node.
=> Create the `configure self` command

spec/templater_spec.rb, src/templating/missing_parameter_wrapper.rb, src/templating/renderer.rb
This commit causes the entire call stack to be printed when the MissingParameterWrapper returns a nil instead of just the last called method. This is done by wrapping the all return values which tracks the call stack.
See commits for full details of the change
=> Display full stack when a parameter is missing

spec/answers_table_creator_spec.rb, spec/commands/build_spec.rb, spec/node_spec.rb, spec/repo_spec.rb, spec/templating/configuration_spec.rb, src/build_methods/build_method.rb, src/build_methods/self.rb, src/cli_helper/config.yaml, src/commands/build.rb, src/constants.rb, src/exceptions.rb, src/file_path.rb, src/node.rb, src/repo.rb, src/system_command.rb, src/validation/configure.rb
This PR is based of #180. Please merge it first.
Fixes #141 
The `build` command now supports the `self` build type. This `self` build operates the same manner as a regular `basic` node build with a few exceptions. 
When building the `self` node, only the self `build_type` can be used. If the `build_type` is not included, `self` will be implicitly used (without a warning). However if `build_type` is set to anything other than `self`, it will result in an error. Similarly if a regular node tries to use the `self` build type, this will also result in an error.
**tl;dr** Self nodes must use the self build_type. Regular nodes can not use the self build_type
The self build_type, uses the `repo/self/default` template. This can be override in `template` section in the config same as any other …
=> Support the `build self` command

spec/validation/configure_spec.rb, src/constants.rb, src/repo.rb, src/validation/configure.rb, src/validation/errors.yaml, src/validation/loader.rb
This PR is based off #180. Please merge that into develop first. Then rebase `refactor/configure` on develop.
This PR is the first in a series to refactor the configurator. A future PR will contain the `Saver` method for answer files and then once the `GUI` is merged, `Configurator` can be refactored to accommodate the update. Note that this PR is being merged into a separate branch. That is because this PR will break `Metalware` until the `Configurator` is refactored.
The major change in this PR is updating the data structure the configure file uses. The updated data structure can be found in `configure.yaml` on the branch listed below. That branch on `metalware-default` needs to be merged in once the refactoring is complete.
https://github.com/alces-software/metalware-default/tree/fix/co …
=> Switch data structure for configure questions and improve validation

spec/validation/answer_spec.rb, spec/validation/saver_spec.rb, src/exceptions.rb, src/validation/answer.rb, src/validation/load_save_base.rb, src/validation/loader.rb, src/validation/saver.rb
It is ideal that we validate answer files before we save them to prevent an error from being saved in the first place.
This PR contains the `Saver` class that broadly operates like the `Loader` class. However it uses some meta programming to insure the first input argument is always the data.
The answer validator had to be updated so it could take a hash directly to validate instead of a file path. Also the shared code between the `Loader` and `Saver` have been extracted to a shared class.
NOTE: This is being merged into the `refactor/configure` branch as it is required by the `Configurator`
=> Implement Saver class for file validation

spec/answers_table_creator_spec.rb, spec/command_helpers/configure_command_spec.rb, spec/commands/configure/domain_spec.rb, spec/commands/configure/group_spec.rb, spec/commands/configure/node_spec.rb, spec/configurator_spec.rb, spec/minimal_repo.rb, spec/node_spec.rb, spec/repo_spec.rb, spec/templating/group_namespace_spec.rb, spec/validation/answer_spec.rb, spec/validation/configure_spec.rb, spec/validation/saver_spec.rb, src/command_helpers/configure_command.rb, src/commands/configure/domain.rb, src/commands/configure/group.rb, src/commands/configure/node.rb, src/configurator.rb, src/exceptions.rb, src/repo.rb, src/validation/answer.rb, src/validation/configure.rb, src/validation/errors.yaml, src/validation/load_save_base.rb, src/validation/loader.rb, src/validation/saver.rb
The large number of commits in this PR is the culmination of work dealing with the `configure.yaml` questions and the `Configurator`.
The three broad sections of commits are:
- Change the `configure.yaml` data structure to be based on an array. This has simplified the validation significantly. Also the last stage of the `Validation` is to convert to the previous hash format so `Metalware` has not changed internally.
- Implement the file `Saver`. This allows answer files to be validated before they are saved.
- Refactor `Configurator` to reduce the number of inputs. It previously had inputs which where only used for testing purposes (e.g. `Highline`) which have been removed and the objects mocked instead. The `higher_level_answers` could also be determined internally to `Configurator` so …
=> Refactor Configurator and change data structure

spec/commands/configure/node_spec.rb, spec/node_spec.rb, spec/templater_spec.rb, spec/templating/group_namespace_spec.rb, src/cli.rb, src/command_helpers/configure_command.rb, src/commands/configure/self.rb, src/configurator.rb, src/dns/named.rb, src/exceptions.rb, src/file_path.rb, src/templating/configuration.rb, src/templating/missing_parameter_wrapper.rb, src/validation/answer.rb, src/validation/load_save_base.rb
This PR will contain commits for various bugs that need ironing out for the `2017.1.0` release of metalware. Please refer to commit messages for greater detail of each bug fix.
The first bug is `configure self` doesn't use the `self` question. This is fixed in https://github.com/alces-software/metalware/pull/198/commits/c577efe138f58989301df4f9732c6525d0f9c8a9 and fixes #193 
https://github.com/alces-software/metalware/pull/198/commits/adafe584ed037322f2513030985c45fe9757e3a0 fixes the array indexing issue by removing the legacy code used for indexing as it is no longer required. Fixes the issue raised #192 (however additional issues may persist). 
The additional bug in named was due to metalware trying to loop through multiple bash commands when their is only 1 command. Fixes #197, …
=> Fixing various bugs for v2017.1.0 release

src/configurator.rb, src/patches/highline.rb, src/validation/load_save_base.rb
The first bug fix is when `configure group` failed to validate any answers. This was because it was looking for the `groups` questions instead of the `group`.
The second commit displays the default for choice questions. fixes #199
=> Fixes the `configure group` and choices bugs

src/deployment_server.rb
Rather than defaulting to `eth0`, which may not exist depending on the host setup, default to the first network interface, which should always exist. This should work better as a more robust default build interface.
Afaics this appears to work fine, @ColonelPanicks you may want to test and merge with your real usage.
=> Always default build interface to valid interface

spec/build_files_retriever_spec.rb, src/build_files_retriever.rb, src/data.rb, src/input.rb, src/namespaces/mixins/alces_static.rb, src/namespaces/node.rb
Previous the build files would be retrieved for every node. This was causing the same network request to be made multiple times. Instead, the network request will be cached so it is only made once. To facilitate this, all the nodes now share a `BuildFilesRetriever` object of `alces`.
Also fixed a bug where the logging in `DeploymentServer` was breaking the cli. This is because `DeploymentServer` sometimes tries to load a file (through ` Data`) before logging is set up.
=> Speed up the build files retrieval process

src/build_methods/local.rb, src/hash_mergers/answer.rb
The bug where the local node answer still exists for the defaults. This commit makes sure the local answers defaults (contained within `configure.yaml`) are used for the local node.
Fixes #233
=> Follow up fix for local answers

spec/alces_utils.rb, spec/file_path_spec.rb, spec/namespaces/alces_spec.rb, spec/namespaces/node_spec.rb, src/deployment_server.rb, src/exceptions.rb, src/namespaces/alces.rb, src/namespaces/hash_merger_namespace.rb, src/namespaces/local.rb, src/namespaces/node.rb
Previously the `config` and `answer` was dumped into the `dynamic_namespace` along with the `node` or `group` that is in scope. However this causes a few issues because it means the `config` may not match what is in scope. Also it meant a weird domain redirect was required if the scope was not specified.
Instead a `scope` method has been defined. It can be:
1. The domain by default
1. A group namespace if a `group:` key appears in the dynamic namespace
1. A node namespace if a `node:` key appears in the dynamic namespace
1. Errors if both `group:` and `node:` are in the dynamic namespace
This means the `config` and `answer` can be delegated to the scope to ensure they are always correct.
It also means that `node` and `group` do not need to go through `method_missing`. Instead they are …
=> Improve scoping for the Alces namespace and bug fixes

spec/alces_utils.rb, spec/alces_utils_spec.rb, spec/command_helpers/configure_command_spec.rb, spec/commands/configure/domain_spec.rb, spec/commands/configure/group_spec.rb, spec/commands/configure/node_spec.rb, spec/commands/remove/group_spec.rb, spec/configurator_spec.rb, spec/group_cache_spec.rb, spec/hash_mergers/metal_recursive_open_struct_spec.rb, spec/templater_spec.rb, src/command_helpers/configure_command.rb, src/commands/configure/domain.rb, src/commands/configure/group.rb, src/commands/configure/local.rb, src/commands/configure/node.rb, src/config.rb, src/configurator.rb, src/group_cache.rb, src/namespaces/alces.rb, src/namespaces/mixins/alces_static.rb
Fixes #251 
Previously `metal configure node` would fail if a node does not belong to a group. This is because there is no mechanism to add single nodes to the genders file and thus metalware.
It is now possible to add single nodes to an orphan group. This is done when a node that does not exist is configured with `metal configure node`. It will automatically be added to the orphan group. A warning is issued however as there is no mechanism to remove it from the orphan group if it is later reconfigured.
The `local` group has been replaced by the `orphan` group. This means it has a group index of 0 and the `local` node will belong to it. The updated genders template (see link below) will automatically detect the local node as an orphan. …
=> Allow orphan nodes to be configured without a group

spec/build_event_spec.rb, spec/commands/configure/group_spec.rb, spec/config_spec.rb, spec/group_cache_spec.rb, spec/integration/build_spec.rb, src/build_event.rb, src/commands/build.rb, src/commands/configure/group.rb, src/config.rb, src/configurator.rb, src/constants.rb, src/file_path.rb, src/group_cache.rb, src/namespaces/node.rb
Fixes #207 
Metalware will now respond to events written to `/v/l/m/events/<node>/<event>` during the build process. Metalware will display the name and content of any file written to a directory of a building node. The build complete file has also been moved to this directory. A file called `complete` will tell metalware that the node has finished building.
To facilitate the change a new `BuildEvent` class has been created. It handles running all of the build hooks in separate threads and detecting if the build has finished. This has allowed for the simplification of the build process.
Also fixed a bug concerning the orphan nodes. See the following commit for full details:
https://github.com/alces-software/metalware/commit/13bdf86b5d4f85014344f8544b6d386dd309612b
=> Support build events sending messages

spec/alces_utils.rb, spec/build_event_spec.rb, spec/commands/build_spec.rb, src/commands/build.rb
Small bug fix. The `run_all_complete_hook` is now located in the `build_event`
=> Fixes #253, Run run_all_complete_hooks on build_event

spec/alces_utils.rb, spec/alces_utils_spec.rb, spec/commands/build_spec.rb, spec/integration/build_spec.rb
The `build` tests use to print a huge amount of warnings during the tests. This is because the nodes with a mocked `hexadecimal` ip address where being deleted and recreated. This meant the rendering scripts where failing.
Instead the old node objects are now preserved. Also the `hexadecimal` ip address is now automatically mocked for all mocked nodes.
The stdout of the build tests are also suppressed as `rspec` will automatically answer the questions regardless of what is displayed.
=> Remove and suppress the output during the tests

spec/build_event_spec.rb, spec/commands/build_spec.rb, spec/integration/build_spec.rb, spec/namespaces/alces_spec.rb, spec/templating/nil_detection_wrapper_spec.rb, src/build_event.rb, src/file_path.rb, src/namespaces/alces.rb, src/templating/nil_detection_wrapper.rb
This PR contains a few bug fixes that where either detected or directly responsible for parsing error bug (fixes #264).
1. Initially it was suspected that the parser error was because the dynamic namespace didn't have a templating block to use. It was unrelated, however the fix is included as it is best practice for MetalROS to be initialised with a template_block. https://github.com/alces-software/metalware/commit/f827249616ebb7af649c3d1f71189438f300d9a9
1. The `FalseClass` being true was due to the `NilDetectionWrapper` always being `truthy`. The fix is to never wrap falsy values. `NilDetectionWrapper` has been updated to handle `nil` and `false` in a similar way (except `nil` issues a warning). https://github.com/alces-software/metalware/commit/be20cb494b2859324a0c7f17efea4031168e4896 …
=> Fix various interconnected bugs

.rubocop_todo.yml, Gemfile, Gemfile.lock, spec/commands/configure/domain_spec.rb, spec/commands/plugin/disable_spec.rb, spec/commands/plugin/enable_spec.rb, spec/commands/plugin/list_spec.rb, spec/filesystem.rb, src/cli.rb, src/cli_helper/config.yaml, src/command_helpers/base_command.rb, src/commands/plugin/disable.rb, src/commands/plugin/enable.rb, src/commands/plugin/list.rb, src/constants.rb, src/file_path.rb, src/plugins.rb
This PR adds the `plugin` command with subcommands to `list`, `enable`, and `disable` plugins. Plugins are (for now at least) considered to be any directories within `/var/lib/metalware/repo/plugins`. Currently these commands are fairly unnecessary since no files within any plugins are being used in any way; this will be added in a future PR.
I'm just going to merge this straight through since it's relatively straightforward, but feel free to add comments if you have any.
=> Plugin commands

scripts/install
I've seen this error far too many times lately, here is a quick fix
=> Don't attempt to copy `templates` dir that no longer exists. Fixes #267

.rubocop_todo.yml, Gemfile, Gemfile.lock, bin/install-ci-dependencies, bin/setup, scripts/os/el6.sh, scripts/os/el7.sh, spec/alces_utils_spec.rb, spec/command_helpers/configure_command_spec.rb, spec/filesystem.rb, src/cli_helper/config.yaml, src/command_helpers/node_identifier.rb, src/command_helpers/orchestrate_command.rb, src/commands/configure/domain.rb, src/commands/configure/local.rb, src/commands/console.rb, src/commands/ipmi.rb, src/commands/orchestrate.rb, src/commands/orchestrate/create.rb, src/commands/orchestrate/destroy.rb, src/commands/render.rb, src/commands/sync.rb, src/commands/view_answers/domain.rb, src/vm.rb
This addresses #242 
- Added `ruby-libvirt` gem and required setup tasks
- Added `orchestrate create` and `orchestrate destroy` commands
- Modified `power` command to detect whether a node is a virtual machine or not, and act accordingly
- Added new `Vm` class, acting as a wrapper around the Ruby Libvirt library
Still to-do, some pending discussion:
=> KVM orchestration

CHANGELOG.md, spec/namespaces/alces_spec.rb, src/cli.rb, src/namespaces/alces.rb
See: https://github.com/alces-software/metalware/commit/f001dcf53eba43f4c0dd70df2dc33667f5156ede
Fixes: #278
=> Preserve the dynamic-stack when multi-threaded

src/vm.rb, src/vm/certificate.rb
Addresses #280 - generates certificates for a `node`s `libvirt_host` the first time `Vm` class is run. These certificates have to be manually copied to the Libvirt host, then the command re-run afterwards.
=> Certificate generation

spec/validation/configure_spec.rb, spec/validation/loader_spec.rb, src/hash_mergers/hash_merger.rb, src/validation/configure.rb, src/validation/loader.rb
This PR contains some refactoring of these classes to remove some unnecessary stuff and better separate what's handled by each class; a test covering the existing `Loader` behaviour is also included. See commits for full details of each change.
This is all in preparation for having the `Loader` also load configure questions for plugins, which will occur in a future PR; I'm submitting this separately in case you want to look at this PR independently to check I've not overlooked anything while doing this.
=> `Validation::Loader` and `Validation::Configure` refactoring

spec/filesystem.rb, spec/validation/loader_spec.rb, src/plugins.rb, src/validation/loader.rb
This PR adds support for configuring enabled plugins via the standard `metal configure` process. It's based on https://github.com/alces-software/metalware/pull/291 so take a look at that first.
The key commit here is https://github.com/alces-software/metalware/commit/6512013b8541a87f1b84452b6a09b5e6a0facf2d, which contains the main change to loading of configure questions and a rough test for this, as well as an overall description of how this works. Later commits then mostly contain refactoring to tidy things up following this change, apart from https://github.com/alces-software/metalware/commit/c7644f15e0cc432664b28217021b464918e40cc6 which adds handling for the situation where no `configure.yaml` file exists for a plugin. So it would be particularly useful if you could take a look at …
=> Plugin configuration

src/commands/ipmi.rb
This addresses #296 - the whole `node` object was being given when it just requires `node.name` in order to correctly run. Also added `-I lanplus` to the rendered command as @ColonelPanicks pointed out this is required.
Tested this on @ColonelPanicks running controller
=> IPMI command fixes

spec/filesystem.rb, spec/namespaces/node_spec.rb, spec/validation/loader_spec.rb, src/constants.rb, src/namespaces/node.rb, src/namespaces/plugin.rb, src/plugins.rb
@WilliamMcCumstie Don't know if you want to have a quick look at this to check I'm not doing anything completely the wrong way with all the namespace stuff? There's not much in this PR, this is just the first step for making a `plugins` field containing information on the enabled plugins for each node available in the node namespace.
I'm submitting this now so I can merge some other stuff based on this, and then later submit some smaller PRs adding for you to have a look at adding the main parts of the plugin namespace.
=> Initial plugin access in node namespace

spec/namespaces/plugin_spec.rb, src/hash_mergers/plugin_config.rb, src/namespaces/node.rb, src/namespaces/plugin.rb
This PR adds support for accessing the plugin config for a node via the plugin namespaces. One plugin namespace is available for every plugin enabled for every node, and is accessible via the `node.plugins` array for each node. The plugin configs are merged in the same way and include the same groups as the containing node namespace's configs.
As with https://github.com/alces-software/metalware/pull/299 I'm going to merge this straight through so I can also merge branches based on this, but would be useful if you could take a look when you get a chance as this touches a lot of the namespaces stuff.
=> Plugin configs

src/commands/template.rb
This was missed in the recent refactor to remove the Config class (see https://github.com/alces-software/metalware/pull/303). This class now no longer exists and this argument is unneeded. Likely this was missed as there is no test coverage for the `template` command and I must have missed it when grepping for leftover usage of Config.
=> Remove missed reference to Config

spec/commands/console_spec.rb, spec/commands/ipmi_spec.rb, spec/commands/power_spec.rb, src/cli_helper/config.yaml, src/commands/console.rb, src/commands/ipmi.rb, src/commands/power.rb
This PR:
- fixes #304, by adding a new `--sleep`/`-s` argument to `power` which tells it to sleep for this long between each power command; this defaults to 0.5 (seconds);
- adds a few smoke tests to the `ipmi`, `power`, and `console` commands so we have some test coverage for these;
- fixes a few minor issues and inconsistencies with these commands;
- refactors these commands a little bit to make the control flow a bit more obvious and less convoluted.
=> Fix various power and ipmi issues

spec/commands/build_spec.rb, spec/commands/console_spec.rb, spec/commands/each_spec.rb, spec/commands/ipmi_spec.rb, spec/commands/power_spec.rb, spec/commands/remove/group_spec.rb, spec/integration/build_spec.rb, spec/namespaces/node_spec.rb, spec/nodeattr_interface_spec.rb, src/cli_helper/config.yaml, src/command_helpers/node_identifier.rb, src/commands/build.rb, src/commands/ipmi.rb, src/commands/remove/group.rb, src/gui/app/models/group.rb, src/namespaces/group.rb, src/namespaces/node.rb, src/nodeattr_interface.rb
Fixes #286 
Relatively small PR to allow metal commands to run on non-primary groups.
The first commit renames one of the `nodeattr` commands. Metalware makes a distinction between `groups` (which are configured) and `genders` which come from the genders file. The command actually returns nodes in a gender and not nodes in a group.
From this, `alces.groups.<name>.nodes` returns all the nodes in the `gender` called name. Thus not all the nodes belong to that primary group. This means using the namespace to get the list of nodes unnecessarily limits the commands to primary groups.
Instead the nodeattr query is directly done by the command allowing secondary groups to be used.
=> Allow metal commands to run on secondary groups

Gemfile.lock, src/cli.rb, src/exceptions.rb
This PR sorts the various different errors into `MetalwareError` and `UserMetalwareError`. It then uses the updated version of `Commander` to suppress the `--trace` prompt when a `UserMetalwareError` is raised.
In the processes of sorting the errors, I have removed the error classes that are no longer being used.
NOTE: The gemfile has not been updated yet. Once the new version of commander has been merged, I will add the final commit.
=> Suppress --trace for user errors

spec/alces_utils.rb, spec/alces_utils_spec.rb, spec/answers_table_creator_spec.rb, spec/build_files_retriever_spec.rb, spec/build_methods/kickstarts/uefi_spec.rb, spec/commands/build_spec.rb, spec/commands/console_spec.rb, spec/commands/ipmi_spec.rb, spec/commands/overview_spec.rb, spec/commands/power_spec.rb, spec/namespaces/domain_spec.rb, spec/namespaces/group_spec.rb, spec/namespaces/node_spec.rb, spec/shared_examples/hash_merger_namespace.rb, src/cli_helper/config.yaml, src/commands/overview.rb, src/file_path.rb, src/namespaces/group.rb, src/nodeattr_interface.rb
This is the first step at implementing #284. The new `overview` command currently displays details about the group.
From the issue description it was determined that the overview command will be dependent on group answers and quite possible configs in the future. To prevent the core metalware repo from becoming dependent on a set answer structure, the content to be displayed is stored in a new repo file `overview.yaml`.
This `overview.yaml` file currently should contain two arrays: `headers` and `fields`. The headers unsurprisingly are the table headers. The fields array contains a list of strings to populate the overview table. All fields are rendered against the group and are intended to use `ERB` tags.
In the process of completing the PR, a bug was detected in `AlcesUtils`. Up until …
=> Implement overview command for groups

src/build_event.rb
Based on #317, please merge it first. Fixes #287 
This branch was going to have multiple fixes, however in the end it only had one. It condenses the output during build to be on a single line. It required a small change to the print method to remove the additional lines.
=> Condense build event output

spec/commands/overview_spec.rb, spec/fixtures/shared_context/overview.rb, spec/overview/table_spec.rb, src/commands/overview.rb, src/namespaces/group.rb, src/nodeattr_interface.rb, src/overview/table.rb
This PR address the issues highlighted in #316 and adds the last few features that fixes #284.
The structure for `overview.yaml` has been updated to use a single array of hashes. This allows the `header` and `value` to be set together and thus prevents issues with length miss-matches. The validation has thus been removed because it will not cause an error anymore.
Instead, if any field is missing, it will be rendered as an empty string. This should make it more flexible to add an removed columns without having to do it all at once.
A domain table has also been added which contains a single row that is rendered in the `domain` scope. Otherwise the table operates in almost the exact same way as the group table with the exception it does not have a name column. To do this, the table …
=> Add an domain overview section/table

Makefile, spec/commands/console_spec.rb, src/commands/console.rb, src/commands/ipmi.rb, src/commands/overview.rb, src/commands/power.rb
This PR fixes #326 (see 
https://github.com/alces-software/metalware/commit/5f001c04d0e9b617e146089d962e30986de53a50 for the main fix). Some related refactoring enabled by the `ipmi`-descended commands now being more similar is also included.
=> Fix wrong host being used for `metal console`

spec/configurator_spec.rb, src/configurator.rb
Fixes #329; see https://github.com/alces-software/metalware/commit/e132297b76a087bc843a03c906dffb728e8316dc for details of issue and fix.
=> Fix re-prompting for boolean questions on initial configure

spec/alces_utils.rb, spec/alces_utils_spec.rb
This allows the mocked version of alces to be reset in the spec. Typically this shouldn't be needed in most cases as only one version of alces exists. However if the command being tested changes a file used to generate `alces`, then it can't be reloaded from within the `spec`.
This change allows greater control over what is being mocked. Please note, any mocked nodes and groups will still exist as they alter the `genders` and `group_cache` files. However mocked `config` and `answer` will be reset as this is done the `alces` object itself.
=> Allow the spec version of `alces` to be reset

spec/alces_utils.rb, spec/commands/configure/group_spec.rb, spec/group_cache_spec.rb, src/commands/configure/group.rb, src/configurator.rb, src/group_cache.rb
Based on #340 , please merge it first.
Previously the orphan nodes where being saved to the `group_cache` right at the beginning of the configure process. This meant exiting it early still resulted in the orphan being added.
The fix is not to implicitly save the `GroupCache` after a node is added. Instead a new `GroupCache.update` method has been created, which can be used instead of `new`. It will yield an instance of the cache and save it at then end. This means if the process exits early, the cache is not saved.
Fixes #341
=> Do not save orphan until the end of the configure process

spec/commands/power_spec.rb, spec/configurator_spec.rb, spec/group_cache_spec.rb, spec/question_tree_spec.rb, src/configurator.rb, src/configurator/question.rb, src/hash_mergers/answer.rb, src/question_tree.rb
Based on #343, please merge it first. This PR fixes #345.
In an attempt to ensure all questions use the same yaml defaults regardless in level, the defaults from non-domain levels where being ignored. This meant that questions that do not get asked at the domain level can not have a default at all.
Instead the yaml defaults at each level are merged in reverse priority order to form the root defaults for all questions. This ensures each question can have a default BUT which default is used is independent of section level.
Also fixes #347 which in the end being an easy fix (see https://github.com/alces-software/metalware/pull/346/commits/6736efdfcf03a58242af3d4d983cb29b67fae7d4). The error was caused by the rendering of the answers during the save process. However the save process should be …
=> Fix merging of `configure.yaml` defaults

spec/commands/ipmi_spec.rb, src/cli_helper/config.yaml, src/commands/console.rb, src/commands/ipmi.rb
Based on #346, please merge it first.
This fixes #348 which raise a very good point that the command input to `ipmi` has been highly volatile. This has been the case for various reasons, without going into depth. However to keep the current `UI` consistent with passed versions, the `-k`, `-c` and `--command` flags have been added back into the `cli`.
They serve no purpose internally within metalware as the command can be inferred by commander automatically. However including them in the command will no longer raise an error.
It does mean however the following command will still error:
```
metal ipmi -c COMMAND -g GROUP_NAME
```
Because the `-c` flag is ignored, metalware will interpret `COMMAND` as the group input and `GROUP_NAME` as the command input. Whilst this might be unexpected, the …
=> Add ipmi command flags back to the cli

CHANGELOG.md
Just combined all previous release candidate notes in this case to avoid
losing any relevant user-facing information about what's included in
this release, although these could probably be made slightly more
concise now they are combined.
=> Update CHANGELOG for 2018.1 [skip ci]

src/configurator/question.rb
This pr implements a fix for #275 by simply converting the default to a string
=> Correctly display integer values during the configure process

spec/utils/editor_spec.rb, src/system_command.rb, src/utils/editor.rb
Opening files in an editor will become a key component of #356.
This utility takes a file path and opens it in the system editor according to `$VISUAL` or `$EDITOR`. If neither are set, then `vi` is used instead.
Most of the commits are concerning the tests. Note that the editor command is not ran during the spec to prevent it opening. Opening the editor during the spec does not play well with `rspec` and creates issues with swap files.
Instead the command is expected to be called with the correct arguments. The ability to open and close the editor has been tested manually. As this action is blocking, as long as the correct command is called the outcome shouldn't change.
=> Create an utility for opening files in an editor

scripts/install, spec/asset_path_spec.rb, spec/filesystem.rb, src/file_path.rb
* Implements the two methods that define the paths for asset templates and save locations; `asset_template` and `asset_final` respectively.
* Adds a `spec` for testing these methods return correct paths
* Replaces any hard coded paths within `FilePath` that simply replicate other method calls with the appropriate method
* Edits the `install` script and `FileSystem` class to include the `/v/l/m/assets` dir in their processes
=> Adding paths to asset files

spec/commands/asset/add_spec.rb, spec/minimal_repo.rb, spec/namespaces/node_spec.rb, src/cli_helper/config.yaml, src/commands.rb, src/commands/asset/add.rb, src/commands/asset/edit.rb, src/namespaces/hash_merger_namespace.rb, src/namespaces/node.rb, src/utils.rb
The `metal asset add` command takes template files from the repo and allows the user to edit them before saving. It is mostly a wrapper around `Editor.open_copy` with a few file checks to ensure the template exists and the asset doesn't.
The `metal asset edit` command has also been added into the `cli` and the file has been create. It otherwise has not been implemented.
The `render_erb_template` method in the `HashMergerNamespace` has also been simplified. This is otherwise unrelated but needed to be done at some point.
=> Implement the add asset command

spec/asset_cache_spec.rb, src/cache/asset.rb, src/file_path.rb
This PR implements functionality and tests for assigning assets to nodes using an asset cache file. It currently stores the relationship in the following format:
```
node:
node001: asset001
node002: asset004
...
```
`data`
* Loads the data and caches it internally
* Initially the file is empty so it creates the necessary structure
`save`
* Saves the data back to `YAML`
`assign_asset_to_node(asset_name, node)`
* Taking a `String` and `Namespaces::Node` as inputs respectively
* Updates the `node` key within the cache file `assets.yaml` using the `asset_name` given as it's value
`asset_for_node(node)`
* Takes `Namespaces::Node` as input
* Returns the value of the key given by `node`
=> Asset Cache

spec/commands/asset/edit_spec.rb, src/commands/asset/edit.rb
`metal asset edit` allows the user to edit an already saved asset using their default editor, just like with `metal asset add`. This will only work on assets that exist so if the user attempts to edit an asset that is non-existent then it will throw back an error message to inform them that the requested asset doesn't exist yet.
=> Implement edit asset command

spec/utils/editor_spec.rb, src/utils/editor.rb
An optional validation block can be provided to the `open_copy` method that will check if the edited file is valid. If the validation passes or if no validation is provided, than the file is moved into place in the same manner as before.
However if the validation fails, than an error is raised. Currently this will trigger the invalid file to be deleted (like it would have been anyway). As this is a `temp` file, the source file remains unchanged. At some point in the future, the invalid files may get cached, however there is issues with scalability if the files are never deleted.
=> Add the ability to validate files after they have been edited

spec/cache/asset_spec.rb, spec/commands/asset/delete_spec.rb, spec/namespaces/node_spec.rb, src/cache/asset.rb, src/cli_helper/config.yaml, src/command_helpers/asset_helper.rb, src/commands/asset/delete.rb, src/commands/asset/edit.rb, src/namespaces/mixins/alces_static.rb, src/namespaces/node.rb
When calling `alces.node.asset` an object should now be returned containing two keys, `name` and `data`. This branch is based off of #368
=> Show the link to the asset when calling 'alces.node.asset'

src/namespaces/mixins/alces_static.rb, src/namespaces/node.rb
=> Rename `alces.asset` to `alces.assets`

spec/alces_utils.rb, spec/cache/asset_spec.rb, spec/commands/asset/link_spec.rb, spec/commands/asset/unlink_spec.rb, spec/utils/editor_spec.rb, src/utils/editor.rb
This PR implements the ability to reopen a temporary `asset` file if it is invalid. When an invalid file is found the user is prompted with a question asking if they wish to reopen the file.
Answering no will discard any changes made to the file and answering yes will allow the user to make changes to the document. However if the file is still invalid after re-editing then they will be prompted again, repeating the process until either the file is valid or they discard the changes.
=> Prompt the user when asset file is invalid

spec/namespaces/asset_array_spec.rb, src/namespaces/asset_array.rb
Turns out, symbols are loaded from ruby when they start with a ":".
Unfortunately, MetalRecursiveOpenStruct does not convert symbols and
thus breaks the referencing between assets.
Instead, assets can reference each other by using "^ASSET_NAME". This
way it is loaded as a String into MetalRecursiveOpenStruct.
Otherwise the conversion is done in the same manner.
=> Change referencing asset from : to ^

spec/build_methods/build_method_spec.rb, src/hash_mergers/metal_recursive_open_struct.rb
The build files render has silently broken due to a miss match
between how it is tested and actually used.
RuboCop was used to replace `each { |_k, value| ... }` with the
`each_value { v ... }` syntax. This works fine for a Hash however
MetalRecursiveOpenStruct does not implement `each_value` and
returns nill instead.
However the build method was being tested with a `Hash` and thus
passed. The test has now been updated to use MetalROS.
The bug was fixed by adding a `each_value` method to MetalROS.
The initialization of MetalROS has also been updated so it
includes a default string conversion block that just returns the
raw string. This should make using it in the tests easier.
=> Test build files with the correct data structure

spec/cache/asset_spec.rb, src/cache/asset.rb
We have increasingly seen the need to have a way of updating the asset cache in place. This PR adds the `Cache::Asset.update` method to do this.
I have held off from updating the asset commands to utilise this method until the `CommandHelpers::AssetHelper` is cleaned up.
=> Method for updating the asset cache

src/command_helpers/has_asset_concern.rb, src/command_helpers/record_editor.rb, src/commands/asset/delete.rb, src/commands/asset/edit.rb, src/commands/asset/link.rb, src/commands/asset/unlink.rb
Within this is a small collection of changes to utilise the `Cache::Asset.update` method added in #388. These changes now mean that the cache is saved in place where appropriate. 
With these changes it also became apparent that `asset_cache` was serving no purpose any more and so I have removed it from `HasAssetConcern`
=> Utilise the update cache method

spec/alces_utils.rb, spec/commands/asset/add_spec.rb, spec/namespaces/asset_array_spec.rb, spec/records/path_spec.rb, src/cli.rb, src/commands/asset/add.rb, src/config.rb, src/file_path.rb, src/records/path.rb
Asset files are now stored in sub directories by `asset_type`. It is a simple case of updating the file path method to take a directory name to be used.
By convention, the directory name is a plural as it is a collection of file. Rails `inflections` are used to do the pluralisation. The `chassis` type however as an irregular inflection as the plural is also `chassis`.  This has been manually configured as `rails` by default pluralises it to `chasses`.
Now that the structure has been updated, the legacy paths are no longer supported and will not be detected by `Record::Path`
=> Store the asset files in sub directories by type

data/asset_types/chassis.yaml, data/asset_types/disk_array.yaml, data/asset_types/network.yaml, data/asset_types/network_adapter.yaml, data/asset_types/network_switch.yaml, data/asset_types/pdu.yaml, data/asset_types/psu.yaml, data/asset_types/rack.yaml, data/asset_types/server.yaml, scripts/install, spec/commands/asset/add_spec.rb, spec/filesystem.rb, spec/minimal_repo.rb, src/file_path.rb
All asset files within [metalware-default](https://github.com/alces-software/metalware-default) have been moved within `Metalware` itself, housed within `data/asset-types/`. 
The PR https://github.com/alces-software/metalware-default/pull/28 removes them from the repo and should be looked at in tandem with this one.
=> Move asset types from the repo

spec/commands/asset/add_spec.rb, spec/records/asset_spec.rb, src/commands/asset/add.rb, src/records/asset.rb
To prevent confusion in the future, assets can not have the same name as types or there plural. Also because the assets are going to be loaded into `Namespaces::AssetArray`, they can not share the name with any of its methods.
To do this, the `Record::Asset.avaliable?` method now checks for these reserved terms. This means that `Asset.avaliable?` can no longer tell if an asset exists or not. To check for an assets existence, `Asset.path` should be used.
=> Reserve the asset types and certain methods from being asset names 

spec/namespaces/asset_array_spec.rb, src/namespaces/asset_array.rb
The type associated with an asset is now stored in it's metadata, based on the directory the asset is located within.
=> Add asset type to the metadata

spec/namespaces/asset_array_spec.rb, spec/shared_examples/record.rb, src/namespaces/asset_array.rb, src/records/record.rb
The assets can now be accessed by type within the namespace. When a new `AssetArray` is created, it dynamically creates a new sub `AssetArray's` corresponding to each asset type. This means the following syntax is supported. The asset methods are always defined as the plural of the asset type.
```
alces.assets.pdus.each { ... }
```
The sub asset arrays are also of the `AssetArray` type and share the loader objects from the parent object. This means regardless of how the asset is accessed, the asset file is only loaded once as all objects share the same cache.
As all the assets within a sub `AssetArray` share an asset type, they do not need the asset methods. For this reason, sub `AssetArray's` do not need to define the asset type methods. Thus the following method call will fail:
``` …
```
=> Load the assets by type into the namespace

spec/commands/asset/add_spec.rb, spec/commands/layout/add_spec.rb, spec/shared_examples/asset_command_that_assigns_a_node.rb, spec/shared_examples/record_add_command.rb, src/cli_helper/config.yaml, src/commands/asset/add.rb, src/commands/layout/add.rb, src/records/record.rb
Using `metal layout add LAYOUT_TYPE LAYOUT_NAME` you can create a new layout from the base of a given `type`. These layouts are stored under `/v/l/m/layouts/<type>/<layout-name>`. 
This command uses the same structure as `asset add` and utilises the same sort of validation thanks to the `Records` class. Therefore you're unable to add from a non-existent type or use a layout name that would cause a conflict, from an existing layout or from any reserved names.
Also within this branch is a new shared example for testing, `record_add_command`, that groups together all tests that are shared between both `asset add` and `layout add`. Because of this changes have been made to the test spec for `asset add` to make use of this new shared example.
=> Implement the layout add command

spec/records/layout.rb, src/records/layout.rb
The `base_path` method within `Records::Layout` checks the given input within the list of `types` and existing `layouts`. Returning the respective path if something is found or raising an error if nothing is found in either place.
From there the path can be used as the base of the asset to be created. This utility was made in preparation for the upcoming changes to `asset add` that allow an asset to be created from a layout or a type.
=> Add a utility for finding an asset type or layout by name

src/commands/layout/add.rb
This implements a fix that ensures the input `ASSET_TYPE` for `metal layout add` is valid before the directory is made. Currently the validity check happens after the directory for the type is made, before it even knows whether or not the type exists.
=> Ensure the source type is valid before making a directory

.rubocop.yml, spec/asset_builder_spec.rb, spec/records/layout_spec.rb, spec/spec_helper.rb, spec/spec_utils.rb, src/asset_builder.rb, src/output.rb, src/records/layout.rb
A new `AssetBuilder` class has been added to manege the creation of assets and sub assets. The key feature of the class is an internal `queue` that will store the assets that need to be created.
By using this `queue`, each asset can be created in order as well as scheduling new assets to be made.
A new asset can be scheduled using the `push_asset` method. It takes a `layout` (or type) and a asset `name`. It then stores this information in the queue. The method for finding an layout or type path has been moved out of `Records::Layout` and into `AssetBuilder` as this is where it is used.
Note: AssetBuilder will store the `type` of an asset in the struct as well. However the code to do this has not been implemented yet. Hence there is a place holder atm.
=> Create `AssetBuilder` that will be used to create assets

spec/asset_builder_spec.rb, src/asset_builder.rb
Now that `push_asset` has been defined, its corresponding `pop_asset` method is required.
It will return the next asset to be built. As it returns a struct, the edit and save methods will be defined on it directly. If however there are no more assets, it returns nil. This means the `empty?` method is not required as `pop_asset` can be performed in a loop until it returns nil.
`pop_asset` is also responsible for checking if the asset already exists. If it does, it skips the asset and returns the next one on the stack (or `nil`). It is assumed that if the asset already exists, the user has intentionally made it and thus no warning should be issued.
=> Define method for getting the next asset

spec/asset_builder_spec.rb, src/asset_builder.rb, src/command_helpers/record_editor.rb, src/utils.rb, src/utils/editor.rb, src/validation/asset.rb
This PR implements the methods require to save an asset file. There are two version of how this can be done:
1. `asset.save` which will trigger the asset to be directly saved
1. `asset.edit_and_save` which will open the asset in an editor before saving it
The `edit_and_save` uses the same prompts as before if the asset is invalid. The `save` does not however as this indicates an issue with the `layout` file. If the `layout` is invalid, than it will just error.
Finally both the `edit_and_save` and `save` methods will copy the asset via a temporary file. The code to do this has been extracted to `Utils` so it can be shared. The purpose of doing this is so the name transformation can occur in the temporary file.
=> Implement methods for saving asset files

spec/namespaces/node_spec.rb, src/namespaces/node.rb
It is common to check if a node is local and the way to do so currently is to call `alces.node.name == 'local'`. This PR implements a `local?` method that allows for calling `alces.node.local?` that returns a boolean for whether or not the node is local.
=> Method for checking if a node is local

spec/asset_builder_spec.rb, src/asset_builder.rb, src/validation/asset.rb
Sorry for the big commits. I got a bit carried away.
Before an asset is saved, it needs to look for the sub asset syntax (`type^asset_name`). When this occurs, the string needs to be translated to its final name: `^#{parent_asset_name}_#{sub_asset_name}`. It also needs to schedule the sub assets to be built.
=> Implement the sub asseting within `AssetBuilder`

spec/asset_builder_spec.rb, src/asset_builder.rb
This PR implements an `edit_asset` method within `AssetBuilder`. This first creates an internal `Asset` before calling the `edit_and_save` method.
=> Edit asset within AssetBuilder

spec/shared_examples/record_add_command.rb, src/asset_builder.rb, src/command_helpers/asset_editor.rb, src/commands/asset/add.rb, src/commands/asset/edit.rb
This PR does not implement any new features. The `asset add/ edit` commands perform the same tasks as before. The sub asseting will not fully work at this stage,
Instead, the asset commands no longer inherit of the `LayoutEditor`. Instead the solely use the `AssetBuilder` to `add/ edit` there assets.
A single test has been skipped as it is no longer compatible between both the `layout add` and `asset add` commands. This will be fixed in a future PR.
=> Integrate AssetBuilder into asset add/ edit commands

spec/command_helpers/alces_command_spec.rb, spec/commands/asset/add_spec.rb, spec/commands/layout/add_spec.rb, spec/shared_examples/record_add_command.rb, src/cli_helper/config.yaml, src/command_helpers/alces_command.rb, src/commands/layout/add.rb, src/commands/view.rb
This PR fixes the spec issue with adding a layout/ asset from a `layout` that doesn't exist. It also fixes a few issues with the `view command`. See commits for details.
Fixes #285
=> Miscellaneous fixes

spec/metal_log_spec.rb, spec/spec_helper.rb, src/metal_log.rb
Based on #421, please merge it first.
To reduces the screen noise, warnings are now only printed to the screen the first time they occur. After this, they are still logged to the file but will not be shown to the user.
This provides a happy median of recording how often a warning is being issued but only showing the relevant information to the user.
Fixes #182
=> Reduce the warnings that are causing screen noise

spec/managed_file_spec.rb, spec/staging_spec.rb, src/dns/named.rb, src/managed_file.rb, src/staging.rb
- Add test coverage for existing `ManagedFile.content` behaviour.
- Add ability to specify different `comment_char` to use when rendering `ManagedFile.content` markers and info.
- Refactor `ManagedFile` to reduce duplication following this addition.
- Allow specifying `comment_char` to use when rendering managed files, which will then be passed through to above.
- Use this new functionality to fix #433 by specifying correct comment character (`;`) when rendering these files.
=> Fix invalid named zone file comments

data/asset_types/network_adapter.yaml
As discussed earlier @ColonelPanicks:
> The interface is a property of a particular node's connection to a network, via a network adapter port, rather than a property of the port itself.
> 
> Therefore we have decided to store network adapter ports as an array rather than a hash including the interface, and the canonical source for interface names will be in each node's network configs.
A pretty trivial change but couple of minor things to consider before merging:
1. Are the `port` keys in this file relevant any more? They aren't used in any of the clusters I have access to, and I'm guessing this is the same information that we now have from the (1-based) index of the port in the `ports` array.
2. Do we need to make any corresponding repo changes following this change?
=> Switch NetworkAdapter asset to use new format

bin/setup, spec/namespaces/node_spec.rb, src/namespaces/node.rb
This PR contains a fix for #439, which is also a fix for the the more general issue that all non-Pxelinux/Kickstart build methods were broken. Also included are some `setup` script tweaks to make this possible to work the first time it is run after syncing Metalware to a machine.
@ColonelPanicks can you try this out and let me know if this does/doesn't fix your original issue? @WilliamMcCumstie if this does fix #439 then I'll merge it unless there's some underlying reason why we thought we didn't need the original `to_sym`ing (and so this might need deeper investigation; see https://github.com/alces-software/metalware/commit/e01b30ef39ff9df3ef9c8032fba8e8e685757068#r30002376).
=> Fix build methods

Gemfile, Gemfile.lock, scripts/install, src/build_methods/build_method.rb, src/build_methods/kickstarts/kickstart.rb, src/build_methods/local.rb, src/file_path.rb
This PR fixes #427. It will render all the scripts contained within `/v/l/m/build_hooks` for each node when the build starts. These scripts are than ran on the host machine using `bash`.
Also resolved https://nvd.nist.gov/vuln/detail/CVE-2018-14042 by updating the bootstrap gem.
=> Render and run hook scripts on build

spec/asset_builder_spec.rb, spec/build_files_retrievers/cache_spec.rb, spec/command_helpers/configure_command_spec.rb, spec/commands/asset/add_spec.rb, spec/commands/build_spec.rb, spec/commands/configure/domain_spec.rb, spec/commands/configure/group_spec.rb, spec/commands/configure/node_spec.rb, spec/commands/each_spec.rb, spec/commands/remove/group_spec.rb, spec/dependency_specifications_spec.rb, spec/namespaces/domain_spec.rb, spec/namespaces/node_spec.rb, spec/slow/status/job_spec.rb, spec/slow/status/monitor_spec.rb, spec/spec_helper.rb, spec/spec_utils.rb
Use RSpec's `config.include` feature
(https://relishapp.com/rspec/rspec-core/docs/helper-methods/define-helper-methods-in-a-module#include-a-module-in-all-example-groups)
to make our SpecUtils helper functions be available in all tests.
This means calls to these functions no longer need to pass in the
current example group (when we want to use RSpec assertions etc. within
these), and makes defining these functions simpler; in turn this should
make it simpler to extract shared behaviour across test files.
Going to merge this straight through once CI passes, but feel free to comment.
=> Make test helper functions available in all tests

scripts/install, spec/filesystem.rb, spec/namespaces/alces_spec.rb, src/constants.rb, src/file_path.rb, src/namespaces/mixins/alces_static.rb
Accessing `alces.data.foo` now provides access within the templating namespace to the YAML data stored in the file `/var/lib/metalware/data/foo.yaml`. This provides a way to make arbitrary new data available within the namespace, which will be useful both as part of the Metalware/Underware split, as well as a feature requested by @ColonelPanicks.
Also made the corresponding change to store the `hunter` data in this new namespace, which means Underware no longer needs to know about `hunter`.
=> Generic namespace data loading
